# files.f
../verilog/CSR.v
../verilog/FP_Adder.v
../verilog/FP_Mult.v
../verilog/Hazard.v
../verilog/M1.v
../verilog/M2.v
../verilog/M3.v
../verilog/M4.v
../verilog/M5.v
../verilog/M6.v
../verilog/M7.v
../verilog/Multiplier.v
../verilog/PC.v
../verilog/Reset_sync.v
../verilog/address_decoder.v
../verilog/alu.v
../verilog/apb.v
../verilog/apb_cdc_bridge.v
../verilog/clk_div_fft.v
../verilog/clk_fp_divider.v
../verilog/controller.v
../verilog/data_mem.v
../verilog/derive_clk_gpio.v
../verilog/derive_clk_mul_div.v
../verilog/derive_clk_spi.v
../verilog/divider.v
../verilog/fft_top.v
../verilog/gpio.v
../verilog/handshake_bridge.v
../verilog/instr_mem.v
../verilog/interrupt_arbiter.v
../verilog/mux8_1.v
../verilog/pipeline_reg1.v
../verilog/pipeline_reg2.v
../verilog/pipeline_reg3.v
../verilog/register_file.v
../verilog/riscv_top.v
../verilog/slave_spi.v
../verilog/soc_top.v
../verilog/spi.v
soc_tb.v
